config/routes.rb
Show::Application.routes.draw do
  resources :globals

  resources :auths

  resources :accounts

  resources :redeems

  resources :shares

  resources :beacons

  resources :devices

  resources :sightings

end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  before_action :set_beacon, only: [:show, :edit, :update, :destroy]

  # GET /beacons
  # GET /beacons.json
  def index
    @beacons = Beacon.all
  end

  # GET /beacons/1
  # GET /beacons/1.json
  def show
  end

  # GET /beacons/new
  def new
    @beacon = Beacon.new
  end

  # GET /beacons/1/edit
  def edit
  end

  # POST /beacons
  # POST /beacons.json
  def create
    @beacon = Beacon.new(beacon_params)

    respond_to do |format|
      if @beacon.save
        format.html { redirect_to @beacon, notice: 'Beacon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beacon }
      else
        format.html { render action: 'new' }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beacons/1
  # PATCH/PUT /beacons/1.json
  def update
    respond_to do |format|
      if @beacon.update(beacon_params)
        format.html { redirect_to @beacon, notice: 'Beacon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beacons/1
  # DELETE /beacons/1.json
  def destroy
    @beacon.destroy
    respond_to do |format|
      format.html { redirect_to beacons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beacon
      @beacon = Beacon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beacon_params
      params.require(:beacon).permit(:beacon, :expire_time, :seen_device_id, :seer_device_id)
    end
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/views/beacons/_form.html.erb
<%= form_for(@beacon) do |f| %>
  <% if @beacon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beacon.errors.count, "error") %> prohibited this beacon from being saved:</h2>

      <ul>
      <% @beacon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beacon %><br>
    <%= f.text_field :beacon %>
  </div>
  <div class="field">
    <%= f.label :expire_time %><br>
    <%= f.datetime_select :expire_time %>
  </div>
  <div class="field">
    <%= f.label :seen_device_id %><br>
    <%= f.text_field :seen_device_id %>
  </div>
  <div class="field">
    <%= f.label :seer_device_id %><br>
    <%= f.text_field :seer_device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beacons/edit.html.erb
<h1>Editing beacon</h1>

<%= render 'form' %>

<%= link_to 'Show', @beacon %> |
<%= link_to 'Back', beacons_path %>

app/views/beacons/index.html.erb
<h1>Listing beacons</h1>

<table>
  <thead>
    <tr>
      <th>Beacon</th>
      <th>Expire time</th>
      <th>Seen device</th>
      <th>Seer device</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beacons.each do |beacon| %>
      <tr>
        <td><%= beacon.beacon %></td>
        <td><%= beacon.expire_time %></td>
        <td><%= beacon.seen_device_id %></td>
        <td><%= beacon.seer_device_id %></td>
        <td><%= link_to 'Show', beacon %></td>
        <td><%= link_to 'Edit', edit_beacon_path(beacon) %></td>
        <td><%= link_to 'Destroy', beacon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beacon', new_beacon_path %>

app/views/beacons/new.html.erb
<h1>New beacon</h1>

<%= render 'form' %>

<%= link_to 'Back', beacons_path %>

app/views/beacons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beacon:</strong>
  <%= @beacon.beacon %>
</p>

<p>
  <strong>Expire time:</strong>
  <%= @beacon.expire_time %>
</p>

<p>
  <strong>Seen device:</strong>
  <%= @beacon.seen_device_id %>
</p>

<p>
  <strong>Seer device:</strong>
  <%= @beacon.seer_device_id %>
</p>

<%= link_to 'Edit', edit_beacon_path(@beacon) %> |
<%= link_to 'Back', beacons_path %>