config/routes.rb
Show::Application.routes.draw do
  resources :globals

  resources :auths

  resources :accounts

  resources :redeems

  resources :shares

  resources :beacons

  resources :devices

  resources :sightings

end

app/models/share.rb
class Share < ActiveRecord::Base
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :set_share, only: [:show, :edit, :update, :destroy]

  # GET /shares
  # GET /shares.json
  def index
    @shares = Share.all
  end

  # GET /shares/1
  # GET /shares/1.json
  def show
  end

  # GET /shares/new
  def new
    @share = Share.new
  end

  # GET /shares/1/edit
  def edit
  end

  # POST /shares
  # POST /shares.json
  def create
    @share = Share.new(share_params)

    respond_to do |format|
      if @share.save
        format.html { redirect_to @share, notice: 'Share was successfully created.' }
        format.json { render action: 'show', status: :created, location: @share }
      else
        format.html { render action: 'new' }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shares/1
  # PATCH/PUT /shares/1.json
  def update
    respond_to do |format|
      if @share.update(share_params)
        format.html { redirect_to @share, notice: 'Share was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1
  # DELETE /shares/1.json
  def destroy
    @share.destroy
    respond_to do |format|
      format.html { redirect_to shares_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share
      @share = Share.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_params
      params.require(:share).permit(:expire_time, :device_id, :share_via, :share_to, :share_cred, :share_to, :num_uses, :num_uses_max)
    end
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_form.html.erb
<%= form_for(@share) do |f| %>
  <% if @share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
      <% @share.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expire_time %><br>
    <%= f.datetime_select :expire_time %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.text_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :share_via %><br>
    <%= f.text_field :share_via %>
  </div>
  <div class="field">
    <%= f.label :share_to %><br>
    <%= f.text_field :share_to %>
  </div>
  <div class="field">
    <%= f.label :share_cred %><br>
    <%= f.text_field :share_cred %>
  </div>
  <div class="field">
    <%= f.label :share_to %><br>
    <%= f.text_field :share_to %>
  </div>
  <div class="field">
    <%= f.label :num_uses %><br>
    <%= f.number_field :num_uses %>
  </div>
  <div class="field">
    <%= f.label :num_uses_max %><br>
    <%= f.number_field :num_uses_max %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shares/edit.html.erb
<h1>Editing share</h1>

<%= render 'form' %>

<%= link_to 'Show', @share %> |
<%= link_to 'Back', shares_path %>

app/views/shares/index.html.erb
<h1>Listing shares</h1>

<table>
  <thead>
    <tr>
      <th>Expire time</th>
      <th>Device</th>
      <th>Share via</th>
      <th>Share to</th>
      <th>Share cred</th>
      <th>Share to</th>
      <th>Num uses</th>
      <th>Num uses max</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shares.each do |share| %>
      <tr>
        <td><%= share.expire_time %></td>
        <td><%= share.device_id %></td>
        <td><%= share.share_via %></td>
        <td><%= share.share_to %></td>
        <td><%= share.share_cred %></td>
        <td><%= share.share_to %></td>
        <td><%= share.num_uses %></td>
        <td><%= share.num_uses_max %></td>
        <td><%= link_to 'Show', share %></td>
        <td><%= link_to 'Edit', edit_share_path(share) %></td>
        <td><%= link_to 'Destroy', share, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Share', new_share_path %>

app/views/shares/new.html.erb
<h1>New share</h1>

<%= render 'form' %>

<%= link_to 'Back', shares_path %>

app/views/shares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expire time:</strong>
  <%= @share.expire_time %>
</p>

<p>
  <strong>Device:</strong>
  <%= @share.device_id %>
</p>

<p>
  <strong>Share via:</strong>
  <%= @share.share_via %>
</p>

<p>
  <strong>Share to:</strong>
  <%= @share.share_to %>
</p>

<p>
  <strong>Share cred:</strong>
  <%= @share.share_cred %>
</p>

<p>
  <strong>Share to:</strong>
  <%= @share.share_to %>
</p>

<p>
  <strong>Num uses:</strong>
  <%= @share.num_uses %>
</p>

<p>
  <strong>Num uses max:</strong>
  <%= @share.num_uses_max %>
</p>

<%= link_to 'Edit', edit_share_path(@share) %> |
<%= link_to 'Back', shares_path %>