config/routes.rb
Show::Application.routes.draw do
  resources :globals

  resources :auths

  resources :accounts

  resources :redeems

  resources :shares

  resources :beacons

  resources :devices

  resources :sightings

end

app/models/redeem.rb
class Redeem < ActiveRecord::Base
end

app/controllers/redeems_controller.rb
class RedeemsController < ApplicationController
  before_action :set_redeem, only: [:show, :edit, :update, :destroy]

  # GET /redeems
  # GET /redeems.json
  def index
    @redeems = Redeem.all
  end

  # GET /redeems/1
  # GET /redeems/1.json
  def show
  end

  # GET /redeems/new
  def new
    @redeem = Redeem.new
  end

  # GET /redeems/1/edit
  def edit
  end

  # POST /redeems
  # POST /redeems.json
  def create
    @redeem = Redeem.new(redeem_params)

    respond_to do |format|
      if @redeem.save
        format.html { redirect_to @redeem, notice: 'Redeem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @redeem }
      else
        format.html { render action: 'new' }
        format.json { render json: @redeem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redeems/1
  # PATCH/PUT /redeems/1.json
  def update
    respond_to do |format|
      if @redeem.update(redeem_params)
        format.html { redirect_to @redeem, notice: 'Redeem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @redeem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redeems/1
  # DELETE /redeems/1.json
  def destroy
    @redeem.destroy
    respond_to do |format|
      format.html { redirect_to redeems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_redeem
      @redeem = Redeem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def redeem_params
      params.require(:redeem).permit(:share_id, :device_id)
    end
end

app/helpers/redeems_helper.rb
module RedeemsHelper
end

app/views/redeems/_form.html.erb
<%= form_for(@redeem) do |f| %>
  <% if @redeem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@redeem.errors.count, "error") %> prohibited this redeem from being saved:</h2>

      <ul>
      <% @redeem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :share_id %><br>
    <%= f.number_field :share_id %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.text_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/redeems/edit.html.erb
<h1>Editing redeem</h1>

<%= render 'form' %>

<%= link_to 'Show', @redeem %> |
<%= link_to 'Back', redeems_path %>

app/views/redeems/index.html.erb
<h1>Listing redeems</h1>

<table>
  <thead>
    <tr>
      <th>Share</th>
      <th>Device</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @redeems.each do |redeem| %>
      <tr>
        <td><%= redeem.share_id %></td>
        <td><%= redeem.device_id %></td>
        <td><%= link_to 'Show', redeem %></td>
        <td><%= link_to 'Edit', edit_redeem_path(redeem) %></td>
        <td><%= link_to 'Destroy', redeem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Redeem', new_redeem_path %>

app/views/redeems/new.html.erb
<h1>New redeem</h1>

<%= render 'form' %>

<%= link_to 'Back', redeems_path %>

app/views/redeems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Share:</strong>
  <%= @redeem.share_id %>
</p>

<p>
  <strong>Device:</strong>
  <%= @redeem.device_id %>
</p>

<%= link_to 'Edit', edit_redeem_path(@redeem) %> |
<%= link_to 'Back', redeems_path %>